server:
  port: 7099

#druid的配置
spring:
  druid:
    username: root
    password: 1111
    driverClassName:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.yyt.tx.mjf.mapper: debug