server:
  port: 7098

#druid的配置
spring:
  druid:
    username: root
    password: richart
    driverClassName:  com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.5:3306/richart?serverTimezone=UTC
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster- nodes: 192.168.91.130:9300
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.yyt.tx.mjf.mapper: debug

log:
  path: guns-logs
